"""empty message

Revision ID: ebb1241f8a62
Revises: 
Create Date: 2022-04-18 16:45:15.321281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb1241f8a62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('user_alias', sa.String(), nullable=True))
    op.drop_column('expenses', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'user_alias')
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
